#!/usr/bin/env python3
"""
Multi-language translations for Three Card Roulette
"""

TRANSLATIONS = {
    'en': {
        'welcome': "WELCOME TO THREE CARD ROULETTE!",
        'balance': "Your current balance: ${}",
        'betting_options': "BETTING OPTIONS:",
        'color_bet': "Color Bet (Red/Black) - Pays 2:1",
        'exact_bet': "Exact Card Bet (specific suit) - Pays 3:1", 
        'multiple_bets': "Multiple Bets - Place multiple bets simultaneously",
        'stock_trading': "Stock Trading",
        'inventory': "Inventory",
        'view_stats': "View Statistics",
        'credits': "Credits",
        'quit_game': "Quit Game",
        'joker_note': "Note: If Joker is drawn, you get another draw (no win/loss)",
        'choose_option': "Choose betting option (1-8): ",
        'enter_amount': "Enter bet amount ($1-${}): $",
        'invalid_amount': "Invalid amount. Must be between $1 and ${}",
        'valid_number': "Please enter a valid number.",
        'bet_color': "Bet on (R)ed or (B)lack? ",
        'enter_rb': "Please enter 'R' for Red or 'B' for Black",
        'choose_suit': "Choose exact suit:",
        'hearts_red': "Hearts (Red)",
        'diamonds_red': "Diamonds (Red)",
        'clubs_black': "Clubs (Black)",
        'spades_black': "Spades (Black)",
        'enter_1234': "Enter choice (1-4): ",
        'enter_1234_msg': "Please enter 1, 2, 3, or 4",
        'current_balance': "Current balance: ${}",
        'press_enter': "Press Enter to continue...",
        'invalid_choice': "Invalid choice. Please try again.",
        'shuffling': "Shuffling cards...",
        'press_draw': "Press Enter to draw the winning card...",
        'draw_num': "Draw #{}: {} card is {}!",
        'joker_reroll': "Draw #{}: JOKER! Rolling again...",
        'press_another': "Press Enter for another draw...",
        'bet_wins': "✅ {} bet on {} (${}) WINS ${}!",
        'bet_loses': "❌ {} bet on {} (${}) loses",
        'total_winnings': "🎉 Total winnings: ${}!",
        'total_loss': "💸 Total loss: ${}",
        'new_balance': "Your new balance: ${}",
        'game_over': "💸 You're out of money! Game Over!",
        'restarting_game': "🔄 Restarting with $100...",
        'thanks': "Thanks for playing Three Card Roulette!",
        'final_balance': "Final balance: ${}",
        'multiple_mode': "=== MULTIPLE BETS MODE ===",
        'choose_bet_type': "Choose bet type:",
        'color_bet_short': "Color Bet (Red/Black)",
        'exact_bet_short': "Exact Card Bet (specific suit)",
        'enter_12': "Enter choice (1-2): ",
        'bet_added': "Bet added: {} on {} for ${}",
        'total_bets': "Total bets: ${}",
        'add_another': "Add another bet? (y/n): ",
        'balance_limit': "You've reached your balance limit.",
        'exceed_balance': "Cannot add bet - would exceed balance (${})",
        'red': "Red",
        'black': "Black",
        'color': "color",
        'exact': "exact",
        'hearts': "Hearts",
        'diamonds': "Diamonds", 
        'clubs': "Clubs",
        'spades': "Spades",
        'winning': "winning",
        'select_language': "Select Language / Seleccionar Idioma / Choisir la langue / Sprache wählen:",
        'english': "English",
        'spanish': "Español", 
        'french': "Français",
        'german': "Deutsch",
        'enter_lang': "Enter choice (1-4): ",
        'stats_title': "=== GAME STATISTICS ===",
        'total_bets_made': "Total bets made: {}",
        'total_wins_count': "Total wins: {}",
        'total_losses_count': "Total losses: {}",
        'win_rate': "Win rate: {:.1f}%",
        'total_bet_amount': "Total amount bet: ${}",
        'total_won_amount': "Total amount won: ${}",
        'total_lost_amount': "Total amount lost: ${}",
        'net_profit': "Net profit/loss: ${}",
        'highest_balance_ever': "Highest balance reached: ${}",
        'games_played_count': "Games played this session: {}",
        'game_saved': "Game saved successfully!",
        'game_loaded': "Game loaded successfully!",
        'no_save_file': "No save file found. Starting new game.",
        'session_stats': "This session: {} bets, {} wins, {} losses",
        'stock_menu': "=== STOCK TRADING ===",
        'buy_stocks': "Buy Stocks",
        'sell_stocks': "Sell Stocks",
        'view_market': "View Market Prices",
        'stock_symbol': "Stock: {} ({})",
        'stock_price': "Price: ${:.2f}",
        'shares_owned': "Shares Owned: {}",
        'enter_stock_choice': "Choose option (1-3): ",
        'enter_stock_symbol': "Choose stock (1-5): ",
        'enter_shares': "Enter number of shares: ",
        'buy_success': "✅ Bought {} shares of {} for ${:.2f}",
        'sell_success': "✅ Sold {} shares of {} for ${:.2f}",
        'insufficient_funds': "❌ Insufficient funds",
        'insufficient_shares': "❌ You don't own enough shares",
        'inventory_title': "=== INVENTORY ===",
        'portfolio_value': "Portfolio Value: ${:.2f}",
        'trophies_title': "🏆 TROPHIES:",
        'no_trophies': "No trophies yet - keep playing!",
        'achievement_unlocked': "🎉 ACHIEVEMENT UNLOCKED: {}",
        'trophy_all_gamemode': "All Gamemode Achiever",
        'trophy_triple_rare': "Triple Rare",
        'trophy_millionaire': "Millionaire",
        'trophy_stock_master': "Stock Master",
        'credits_title': "=== CREDITS ===",
        'game_by': "🎮 Game Created by: MATTHIEU",
        'coding_by': "💻 Coding Powered by: CLAUDE AI",
        'ascii_art': "   *** CLAUDE AI ***\n  Artificial Intelligence\n     Coding Assistant"
    },
    'es': {
        'welcome': "¡BIENVENIDO A LA RULETA DE TRES CARTAS!",
        'balance': "Tu saldo actual: ${}",
        'betting_options': "OPCIONES DE APUESTA:",
        'color_bet': "Apuesta de Color (Rojo/Negro) - Paga 2:1",
        'exact_bet': "Apuesta de Carta Exacta (palo específico) - Paga 3:1",
        'multiple_bets': "Apuestas Múltiples - Realiza múltiples apuestas simultáneamente",
        'stock_trading': "Comercio de Acciones",
        'inventory': "Inventario",
        'view_stats': "Ver Estadísticas",
        'credits': "Créditos",
        'quit_game': "Salir del Juego",
        'joker_note': "Nota: Si sale el Comodín, obtienes otro sorteo (sin ganar/perder)",
        'choose_option': "Elige opción de apuesta (1-8): ",
        'enter_amount': "Ingresa cantidad de apuesta ($1-${}): $",
        'invalid_amount': "Cantidad inválida. Debe estar entre $1 y ${}",
        'valid_number': "Por favor ingresa un número válido.",
        'bet_color': "¿Apostar a (R)ojo o (N)egro? ",
        'enter_rb': "Por favor ingresa 'R' para Rojo o 'N' para Negro",
        'choose_suit': "Elige palo exacto:",
        'hearts_red': "Corazones (Rojo)",
        'diamonds_red': "Diamantes (Rojo)",
        'clubs_black': "Tréboles (Negro)",
        'spades_black': "Espadas (Negro)",
        'enter_1234': "Ingresa elección (1-4): ",
        'enter_1234_msg': "Por favor ingresa 1, 2, 3, o 4",
        'current_balance': "Saldo actual: ${}",
        'press_enter': "Presiona Enter para continuar...",
        'invalid_choice': "Elección inválida. Por favor intenta de nuevo.",
        'shuffling': "Barajando cartas...",
        'press_draw': "Presiona Enter para sacar la carta ganadora...",
        'draw_num': "Sorteo #{}: ¡La carta {} es {}!",
        'joker_reroll': "Sorteo #{}: ¡COMODÍN! Sorteando de nuevo...",
        'press_another': "Presiona Enter para otro sorteo...",
        'bet_wins': "✅ ¡Apuesta {} en {} (${}) GANA ${}!",
        'bet_loses': "❌ Apuesta {} en {} (${}) pierde",
        'total_winnings': "🎉 ¡Ganancias totales: ${}!",
        'total_loss': "💸 Pérdida total: ${}",
        'new_balance': "Tu nuevo saldo: ${}",
        'game_over': "💸 ¡Te quedaste sin dinero! ¡Juego terminado!",
        'restarting_game': "🔄 Reiniciando con $100...",
        'thanks': "¡Gracias por jugar Ruleta de Tres Cartas!",
        'final_balance': "Saldo final: ${}",
        'multiple_mode': "=== MODO APUESTAS MÚLTIPLES ===",
        'choose_bet_type': "Elige tipo de apuesta:",
        'color_bet_short': "Apuesta de Color (Rojo/Negro)",
        'exact_bet_short': "Apuesta de Carta Exacta (palo específico)",
        'enter_12': "Ingresa elección (1-2): ",
        'bet_added': "Apuesta agregada: {} en {} por ${}",
        'total_bets': "Apuestas totales: ${}",
        'add_another': "¿Agregar otra apuesta? (s/n): ",
        'balance_limit': "Has alcanzado tu límite de saldo.",
        'exceed_balance': "No se puede agregar apuesta - excedería el saldo (${})",
        'red': "Rojo",
        'black': "Negro",
        'color': "color",
        'exact': "exacta",
        'hearts': "Corazones",
        'diamonds': "Diamantes",
        'clubs': "Tréboles", 
        'spades': "Espadas",
        'winning': "ganadora",
        'select_language': "Select Language / Seleccionar Idioma / Choisir la langue / Sprache wählen:",
        'english': "English",
        'spanish': "Español",
        'french': "Français", 
        'german': "Deutsch",
        'enter_lang': "Ingresa elección (1-4): ",
        'stats_title': "=== ESTADÍSTICAS DEL JUEGO ===",
        'total_bets_made': "Apuestas totales realizadas: {}",
        'total_wins_count': "Victorias totales: {}",
        'total_losses_count': "Derrotas totales: {}",
        'win_rate': "Tasa de victoria: {:.1f}%",
        'total_bet_amount': "Cantidad total apostada: ${}",
        'total_won_amount': "Cantidad total ganada: ${}",
        'total_lost_amount': "Cantidad total perdida: ${}",
        'net_profit': "Ganancia/pérdida neta: ${}",
        'highest_balance_ever': "Saldo más alto alcanzado: ${}",
        'games_played_count': "Juegos jugados esta sesión: {}",
        'game_saved': "¡Juego guardado exitosamente!",
        'game_loaded': "¡Juego cargado exitosamente!",
        'no_save_file': "No se encontró archivo de guardado. Iniciando juego nuevo.",
        'session_stats': "Esta sesión: {} apuestas, {} victorias, {} derrotas",
        'stock_menu': "=== COMERCIO DE ACCIONES ===",
        'buy_stocks': "Comprar Acciones",
        'sell_stocks': "Vender Acciones",
        'view_market': "Ver Precios del Mercado",
        'stock_symbol': "Acción: {} ({})",
        'stock_price': "Precio: ${:.2f}",
        'shares_owned': "Acciones Poseídas: {}",
        'enter_stock_choice': "Elige opción (1-3): ",
        'enter_stock_symbol': "Elige acción (1-5): ",
        'enter_shares': "Ingresa número de acciones: ",
        'buy_success': "✅ Compraste {} acciones de {} por ${:.2f}",
        'sell_success': "✅ Vendiste {} acciones de {} por ${:.2f}",
        'insufficient_funds': "❌ Fondos insuficientes",
        'insufficient_shares': "❌ No tienes suficientes acciones",
        'inventory_title': "=== INVENTARIO ===",
        'portfolio_value': "Valor del Portafolio: ${:.2f}",
        'trophies_title': "🏆 TROFEOS:",
        'no_trophies': "Aún no hay trofeos - ¡sigue jugando!",
        'achievement_unlocked': "🎉 LOGRO DESBLOQUEADO: {}",
        'trophy_all_gamemode': "Triunfador de Todos los Modos",
        'trophy_triple_rare': "Triple Raro",
        'trophy_millionaire': "Millonario",
        'trophy_stock_master': "Maestro de Acciones",
        'credits_title': "=== CRÉDITOS ===",
        'game_by': "🎮 Juego Creado por: MATTHIEU",
        'coding_by': "💻 Programación por: CLAUDE AI",
        'ascii_art': "   *** CLAUDE AI ***\n  Inteligencia Artificial\n    Asistente de Código"
    },
    'fr': {
        'welcome': "BIENVENUE À LA ROULETTE À TROIS CARTES!",
        'balance': "Votre solde actuel: ${}",
        'betting_options': "OPTIONS DE PARI:",
        'color_bet': "Pari Couleur (Rouge/Noir) - Paie 2:1",
        'exact_bet': "Pari Carte Exacte (couleur spécifique) - Paie 3:1",
        'multiple_bets': "Paris Multiples - Placez plusieurs paris simultanément",
        'stock_trading': "Trading d'Actions",
        'inventory': "Inventaire",
        'view_stats': "Voir les Statistiques",
        'credits': "Crédits",
        'quit_game': "Quitter le Jeu",
        'joker_note': "Note: Si le Joker est tiré, vous obtenez un autre tirage (pas de gain/perte)",
        'choose_option': "Choisissez l'option de pari (1-8): ",
        'enter_amount': "Entrez le montant du pari ($1-${}): $",
        'invalid_amount': "Montant invalide. Doit être entre $1 et ${}",
        'valid_number': "Veuillez entrer un nombre valide.",
        'bet_color': "Parier sur (R)ouge ou (N)oir? ",
        'enter_rb': "Veuillez entrer 'R' pour Rouge ou 'N' pour Noir",
        'choose_suit': "Choisissez la couleur exacte:",
        'hearts_red': "Cœurs (Rouge)",
        'diamonds_red': "Carreaux (Rouge)",
        'clubs_black': "Trèfles (Noir)",
        'spades_black': "Piques (Noir)",
        'enter_1234': "Entrez le choix (1-4): ",
        'enter_1234_msg': "Veuillez entrer 1, 2, 3, ou 4",
        'current_balance': "Solde actuel: ${}",
        'press_enter': "Appuyez sur Entrée pour continuer...",
        'invalid_choice': "Choix invalide. Veuillez réessayer.",
        'shuffling': "Mélange des cartes...",
        'press_draw': "Appuyez sur Entrée pour tirer la carte gagnante...",
        'draw_num': "Tirage #{}: La carte {} est {}!",
        'joker_reroll': "Tirage #{}: JOKER! Tirage à nouveau...",
        'press_another': "Appuyez sur Entrée pour un autre tirage...",
        'bet_wins': "✅ Pari {} sur {} (${}) GAGNE ${}!",
        'bet_loses': "❌ Pari {} sur {} (${}) perd",
        'total_winnings': "🎉 Gains totaux: ${}!",
        'total_loss': "💸 Perte totale: ${}",
        'new_balance': "Votre nouveau solde: ${}",
        'game_over': "💸 Vous n'avez plus d'argent! Jeu terminé!",
        'restarting_game': "🔄 Redémarrage avec $100...",
        'thanks': "Merci d'avoir joué à la Roulette à Trois Cartes!",
        'final_balance': "Solde final: ${}",
        'multiple_mode': "=== MODE PARIS MULTIPLES ===",
        'choose_bet_type': "Choisissez le type de pari:",
        'color_bet_short': "Pari Couleur (Rouge/Noir)",
        'exact_bet_short': "Pari Carte Exacte (couleur spécifique)",
        'enter_12': "Entrez le choix (1-2): ",
        'bet_added': "Pari ajouté: {} sur {} pour ${}",
        'total_bets': "Paris totaux: ${}",
        'add_another': "Ajouter un autre pari? (o/n): ",
        'balance_limit': "Vous avez atteint votre limite de solde.",
        'exceed_balance': "Impossible d'ajouter le pari - dépasserait le solde (${})",
        'red': "Rouge",
        'black': "Noir",
        'color': "couleur",
        'exact': "exacte",
        'hearts': "Cœurs",
        'diamonds': "Carreaux",
        'clubs': "Trèfles",
        'spades': "Piques",
        'winning': "gagnante",
        'select_language': "Select Language / Seleccionar Idioma / Choisir la langue / Sprache wählen:",
        'english': "English",
        'spanish': "Español",
        'french': "Français",
        'german': "Deutsch",
        'enter_lang': "Entrez le choix (1-4): ",
        'stats_title': "=== STATISTIQUES DU JEU ===",
        'total_bets_made': "Total des paris effectués: {}",
        'total_wins_count': "Victoires totales: {}",
        'total_losses_count': "Défaites totales: {}",
        'win_rate': "Taux de victoire: {:.1f}%",
        'total_bet_amount': "Montant total parié: ${}",
        'total_won_amount': "Montant total gagné: ${}",
        'total_lost_amount': "Montant total perdu: ${}",
        'net_profit': "Profit/perte net: ${}",
        'highest_balance_ever': "Solde le plus élevé atteint: ${}",
        'games_played_count': "Jeux joués cette session: {}",
        'game_saved': "Jeu sauvegardé avec succès!",
        'game_loaded': "Jeu chargé avec succès!",
        'no_save_file': "Aucun fichier de sauvegarde trouvé. Nouveau jeu commencé.",
        'session_stats': "Cette session: {} paris, {} victoires, {} défaites",
        'stock_menu': "=== TRADING D'ACTIONS ===",
        'buy_stocks': "Acheter des Actions",
        'sell_stocks': "Vendre des Actions",
        'view_market': "Voir les Prix du Marché",
        'stock_symbol': "Action: {} ({})",
        'stock_price': "Prix: ${:.2f}",
        'shares_owned': "Actions Possédées: {}",
        'enter_stock_choice': "Choisissez l'option (1-3): ",
        'enter_stock_symbol': "Choisissez l'action (1-5): ",
        'enter_shares': "Entrez le nombre d'actions: ",
        'buy_success': "✅ Acheté {} actions de {} pour ${:.2f}",
        'sell_success': "✅ Vendu {} actions de {} pour ${:.2f}",
        'insufficient_funds': "❌ Fonds insuffisants",
        'insufficient_shares': "❌ Vous ne possédez pas assez d'actions",
        'inventory_title': "=== INVENTAIRE ===",
        'portfolio_value': "Valeur du Portefeuille: ${:.2f}",
        'trophies_title': "🏆 TROPHÉES:",
        'no_trophies': "Pas encore de trophées - continuez à jouer!",
        'achievement_unlocked': "🎉 SUCCÈS DÉBLOQUÉ: {}",
        'trophy_all_gamemode': "Maître de Tous les Modes",
        'trophy_triple_rare': "Triple Rare",
        'trophy_millionaire': "Millionnaire",
        'trophy_stock_master': "Maître des Actions",
        'credits_title': "=== CRÉDITS ===",
        'game_by': "🎮 Jeu Créé par: MATTHIEU",
        'coding_by': "💻 Programmation par: CLAUDE AI",
        'ascii_art': "   *** CLAUDE AI ***\n  Intelligence Artificielle\n    Assistant de Code"
    },
    'de': {
        'welcome': "WILLKOMMEN BEI DREI-KARTEN-ROULETTE!",
        'balance': "Ihr aktueller Kontostand: ${}",
        'betting_options': "WETTOPTIONEN:",
        'color_bet': "Farbwette (Rot/Schwarz) - Zahlt 2:1",
        'exact_bet': "Exakte Kartenwette (spezifische Farbe) - Zahlt 3:1",
        'multiple_bets': "Mehrfachwetten - Mehrere Wetten gleichzeitig platzieren",
        'stock_trading': "Aktienhandel",
        'inventory': "Inventar",
        'view_stats': "Statistiken anzeigen",
        'credits': "Credits",
        'quit_game': "Spiel beenden",
        'joker_note': "Hinweis: Wenn der Joker gezogen wird, erhalten Sie eine weitere Ziehung (kein Gewinn/Verlust)",
        'choose_option': "Wettoption wählen (1-8): ",
        'enter_amount': "Wetteinsatz eingeben ($1-${}): $",
        'invalid_amount': "Ungültiger Betrag. Muss zwischen $1 und ${} liegen",
        'valid_number': "Bitte geben Sie eine gültige Zahl ein.",
        'bet_color': "Auf (R)ot oder (S)chwarz setzen? ",
        'enter_rb': "Bitte geben Sie 'R' für Rot oder 'S' für Schwarz ein",
        'choose_suit': "Exakte Farbe wählen:",
        'hearts_red': "Herz (Rot)",
        'diamonds_red': "Karo (Rot)",
        'clubs_black': "Kreuz (Schwarz)",
        'spades_black': "Pik (Schwarz)",
        'enter_1234': "Wahl eingeben (1-4): ",
        'enter_1234_msg': "Bitte geben Sie 1, 2, 3, oder 4 ein",
        'current_balance': "Aktueller Kontostand: ${}",
        'press_enter': "Drücken Sie Enter zum Fortfahren...",
        'invalid_choice': "Ungültige Wahl. Bitte versuchen Sie es erneut.",
        'shuffling': "Karten mischen...",
        'press_draw': "Drücken Sie Enter, um die Gewinnkarte zu ziehen...",
        'draw_num': "Ziehung #{}: Die {} Karte ist {}!",
        'joker_reroll': "Ziehung #{}: JOKER! Erneut ziehen...",
        'press_another': "Drücken Sie Enter für eine weitere Ziehung...",
        'bet_wins': "✅ {} Wette auf {} (${}) GEWINNT ${}!",
        'bet_loses': "❌ {} Wette auf {} (${}) verliert",
        'total_winnings': "🎉 Gesamtgewinne: ${}!",
        'total_loss': "💸 Gesamtverlust: ${}",
        'new_balance': "Ihr neuer Kontostand: ${}",
        'game_over': "💸 Sie haben kein Geld mehr! Spiel beendet!",
        'restarting_game': "🔄 Neustart mit $100...",
        'thanks': "Danke fürs Spielen von Drei-Karten-Roulette!",
        'final_balance': "Endkontostand: ${}",
        'multiple_mode': "=== MEHRFACHWETTEN-MODUS ===",
        'choose_bet_type': "Wetttyp wählen:",
        'color_bet_short': "Farbwette (Rot/Schwarz)",
        'exact_bet_short': "Exakte Kartenwette (spezifische Farbe)",
        'enter_12': "Wahl eingeben (1-2): ",
        'bet_added': "Wette hinzugefügt: {} auf {} für ${}",
        'total_bets': "Gesamtwetten: ${}",
        'add_another': "Weitere Wette hinzufügen? (j/n): ",
        'balance_limit': "Sie haben Ihr Kontolimit erreicht.",
        'exceed_balance': "Kann Wette nicht hinzufügen - würde Kontostand übersteigen (${})",
        'red': "Rot",
        'black': "Schwarz",
        'color': "Farb",
        'exact': "exakte",
        'hearts': "Herz",
        'diamonds': "Karo",
        'clubs': "Kreuz",
        'spades': "Pik",
        'winning': "Gewinn",
        'select_language': "Select Language / Seleccionar Idioma / Choisir la langue / Sprache wählen:",
        'english': "English",
        'spanish': "Español",
        'french': "Français",
        'german': "Deutsch",
        'enter_lang': "Wahl eingeben (1-4): ",
        'stats_title': "=== SPIELSTATISTIKEN ===",
        'total_bets_made': "Gesamte Wetten: {}",
        'total_wins_count': "Gesamte Siege: {}",
        'total_losses_count': "Gesamte Verluste: {}",
        'win_rate': "Gewinnrate: {:.1f}%",
        'total_bet_amount': "Gesamter Wetteinsatz: ${}",
        'total_won_amount': "Gesamter Gewinn: ${}",
        'total_lost_amount': "Gesamter Verlust: ${}",
        'net_profit': "Nettogewinn/-verlust: ${}",
        'highest_balance_ever': "Höchster Kontostand erreicht: ${}",
        'games_played_count': "Spiele dieser Sitzung: {}",
        'game_saved': "Spiel erfolgreich gespeichert!",
        'game_loaded': "Spiel erfolgreich geladen!",
        'no_save_file': "Keine Speicherdatei gefunden. Neues Spiel gestartet.",
        'session_stats': "Diese Sitzung: {} Wetten, {} Siege, {} Verluste",
        'stock_menu': "=== AKTIENHANDEL ===",
        'buy_stocks': "Aktien Kaufen",
        'sell_stocks': "Aktien Verkaufen",
        'view_market': "Marktpreise Anzeigen",
        'stock_symbol': "Aktie: {} ({})",
        'stock_price': "Preis: ${:.2f}",
        'shares_owned': "Besitzte Aktien: {}",
        'enter_stock_choice': "Option wählen (1-3): ",
        'enter_stock_symbol': "Aktie wählen (1-5): ",
        'enter_shares': "Anzahl der Aktien eingeben: ",
        'buy_success': "✅ {} Aktien von {} für ${:.2f} gekauft",
        'sell_success': "✅ {} Aktien von {} für ${:.2f} verkauft",
        'insufficient_funds': "❌ Unzureichende Mittel",
        'insufficient_shares': "❌ Sie besitzen nicht genug Aktien",
        'inventory_title': "=== INVENTAR ===",
        'portfolio_value': "Portfolio-Wert: ${:.2f}",
        'trophies_title': "🏆 TROPHÄEN:",
        'no_trophies': "Noch keine Trophäen - weiterspielen!",
        'achievement_unlocked': "🎉 ERFOLG FREIGESCHALTET: {}",
        'trophy_all_gamemode': "Alle-Modi-Meister",
        'trophy_triple_rare': "Triple Selten",
        'trophy_millionaire': "Millionär",
        'trophy_stock_master': "Aktien-Meister",
        'credits_title': "=== CREDITS ===",
        'game_by': "🎮 Spiel Erstellt von: MATTHIEU",
        'coding_by': "💻 Programmierung von: CLAUDE AI",
        'ascii_art': "   *** CLAUDE AI ***\n  Künstliche Intelligenz\n    Code-Assistent"
    }
}